# #MailSlurp API
#
##MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
#
#The version of the OpenAPI document: 6.5.2
#Contact: contact@mailslurp.dev
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 5.1.1
#

require "time"

module 
  class CampaignProbeInsightsDto include JSON::Serializable
   include JSON::Serializable 
    @[JSON::Field(key: probeId, type: String)]
    property probe_id : String


    @[JSON::Field(key: since, type: Time)]
    property since : Time


    @[JSON::Field(key: before, type: Time)]
    property before : Time


    @[JSON::Field(key: totalRuns, type: Int32)]
    property total_runs : Int32


    @[JSON::Field(key: healthyRuns, type: Int32)]
    property healthy_runs : Int32


    @[JSON::Field(key: warningRuns, type: Int32)]
    property warning_runs : Int32


    @[JSON::Field(key: failedRuns, type: Int32)]
    property failed_runs : Int32


    @[JSON::Field(key: successRate, type: Float64)]
    property success_rate : Float64


    @[JSON::Field(key: averageHealthScore, type: Float64)]
    property average_health_score : Float64


    @[JSON::Field(key: currentHealthyStreak, type: Int32)]
    property current_healthy_streak : Int32


    @[JSON::Field(key: bestHealthyStreak, type: Int32)]
    property best_healthy_streak : Int32


    @[JSON::Field(key: goodPerformanceSignals, type: Array(String))]
    property good_performance_signals : Array(String)


    @[JSON::Field(key: attentionSignals, type: Array(String))]
    property attention_signals : Array(String)


    @[JSON::Field(key: topFindings, type: Array(String))]
    property top_findings : Array(String)


    @[JSON::Field(key: latestRun, type: CampaignProbeRunDto)]
    property latest_run : CampaignProbeRunDto

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@probe_id : String, @since : Time, @before : Time, @total_runs : Int32, @healthy_runs : Int32, @warning_runs : Int32, @failed_runs : Int32, @success_rate : Float64, @average_health_score : Float64, @current_healthy_streak : Int32, @best_healthy_streak : Int32, @good_performance_signals : Array(String), @attention_signals : Array(String), @top_findings : Array(String), @latest_run : CampaignProbeRunDto | Nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @probe_id.nil?
        invalid_properties.push("invalid value for \"probe_id\", probe_id cannot be nil.")
      end

      if @since.nil?
        invalid_properties.push("invalid value for \"since\", since cannot be nil.")
      end

      if @before.nil?
        invalid_properties.push("invalid value for \"before\", before cannot be nil.")
      end

      if @total_runs.nil?
        invalid_properties.push("invalid value for \"total_runs\", total_runs cannot be nil.")
      end

      if @healthy_runs.nil?
        invalid_properties.push("invalid value for \"healthy_runs\", healthy_runs cannot be nil.")
      end

      if @warning_runs.nil?
        invalid_properties.push("invalid value for \"warning_runs\", warning_runs cannot be nil.")
      end

      if @failed_runs.nil?
        invalid_properties.push("invalid value for \"failed_runs\", failed_runs cannot be nil.")
      end

      if @success_rate.nil?
        invalid_properties.push("invalid value for \"success_rate\", success_rate cannot be nil.")
      end

      if @average_health_score.nil?
        invalid_properties.push("invalid value for \"average_health_score\", average_health_score cannot be nil.")
      end

      if @current_healthy_streak.nil?
        invalid_properties.push("invalid value for \"current_healthy_streak\", current_healthy_streak cannot be nil.")
      end

      if @best_healthy_streak.nil?
        invalid_properties.push("invalid value for \"best_healthy_streak\", best_healthy_streak cannot be nil.")
      end

      if @good_performance_signals.nil?
        invalid_properties.push("invalid value for \"good_performance_signals\", good_performance_signals cannot be nil.")
      end

      if @attention_signals.nil?
        invalid_properties.push("invalid value for \"attention_signals\", attention_signals cannot be nil.")
      end

      if @top_findings.nil?
        invalid_properties.push("invalid value for \"top_findings\", top_findings cannot be nil.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @probe_id.nil?
      return false if @since.nil?
      return false if @before.nil?
      return false if @total_runs.nil?
      return false if @healthy_runs.nil?
      return false if @warning_runs.nil?
      return false if @failed_runs.nil?
      return false if @success_rate.nil?
      return false if @average_health_score.nil?
      return false if @current_healthy_streak.nil?
      return false if @best_healthy_streak.nil?
      return false if @good_performance_signals.nil?
      return false if @attention_signals.nil?
      return false if @top_findings.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          probe_id == o.probe_id &&
          since == o.since &&
          before == o.before &&
          total_runs == o.total_runs &&
          healthy_runs == o.healthy_runs &&
          warning_runs == o.warning_runs &&
          failed_runs == o.failed_runs &&
          success_rate == o.success_rate &&
          average_health_score == o.average_health_score &&
          current_healthy_streak == o.current_healthy_streak &&
          best_healthy_streak == o.best_healthy_streak &&
          good_performance_signals == o.good_performance_signals &&
          attention_signals == o.attention_signals &&
          top_findings == o.top_findings &&
          latest_run == o.latest_run
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [probe_id, since, before, total_runs, healthy_runs, warning_runs, failed_runs, success_rate, average_health_score, current_healthy_streak, best_healthy_streak, good_performance_signals, attention_signals, top_findings, latest_run].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if !attributes[self.class.attribute_map[key]]? && self.class.openapi_nullable.includes?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        ({} of Symbol => String).tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = .const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {} of Symbol => String
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.includes?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        ({} of Symbol => String).tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
