# #MailSlurp API
#
##MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
#
#The version of the OpenAPI document: 6.5.2
#Contact: contact@mailslurp.dev
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 5.1.1
#

require "time"

module 
  class CreatePhoneNumberOptions include JSON::Serializable
   include JSON::Serializable 
    @[JSON::Field(key: phoneCountry, type: String)]
    property phone_country : String


    @[JSON::Field(key: name, type: String)]
    property name : String


    @[JSON::Field(key: description, type: String)]
    property description : String


    @[JSON::Field(key: tags, type: Array(String))]
    property tags : Array(String)


    @[JSON::Field(key: schedule, type: String)]
    property schedule : String


    @[JSON::Field(key: phoneNumberEndpointOverride, type: String)]
    property phone_number_endpoint_override : String


    @[JSON::Field(key: phoneNumberVariant, type: String)]
    property phone_number_variant : String


    @[JSON::Field(key: phoneProvider, type: String)]
    property phone_provider : String


    # Line-quality preference for simple phone number provisioning
    @[JSON::Field(key: phoneLineFilter, type: String)]
    property phone_line_filter : String

    class EnumAttributeValidator
      getter datatype : String
      getter allowable_values : Array(String)

      def initialize(datatype, allowable_values)
        @datatype = datatype
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.includes?(value)
      end
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@phone_country : String, @name : String | Nil, @description : String | Nil, @tags : Array(String) | Nil, @schedule : String | Nil, @phone_number_endpoint_override : String | Nil, @phone_number_variant : String | Nil, @phone_provider : String | Nil, @phone_line_filter : String | Nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @phone_country.nil?
        invalid_properties.push("invalid value for \"phone_country\", phone_country cannot be nil.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @phone_country.nil?
      phone_country_validator = EnumAttributeValidator.new("String", ["US", "GB", "AU", "CA", "EE", "HK", "PL", "PT", "NL", "IL", "FI", "SE"])
      return false unless phone_country_validator.valid?(@phone_country)
      schedule_validator = EnumAttributeValidator.new("String", ["MONTHLY", "YEARLY"])
      return false unless schedule_validator.valid?(@schedule)
      phone_number_variant_validator = EnumAttributeValidator.new("String", ["LOCAL", "MOBILE", "TOLL_FREE"])
      return false unless phone_number_variant_validator.valid?(@phone_number_variant)
      phone_provider_validator = EnumAttributeValidator.new("String", ["T1", "T2"])
      return false unless phone_provider_validator.valid?(@phone_provider)
      phone_line_filter_validator = EnumAttributeValidator.new("String", ["ANY", "OTP_FRIENDLY", "NON_VOIP"])
      return false unless phone_line_filter_validator.valid?(@phone_line_filter)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_country Object to be assigned
    def phone_country=(phone_country)
      validator = EnumAttributeValidator.new("String", ["US", "GB", "AU", "CA", "EE", "HK", "PL", "PT", "NL", "IL", "FI", "SE"])
      unless validator.valid?(phone_country)
        raise ArgumentError.new("invalid value for \"phone_country\", must be one of #{validator.allowable_values}.")
      end
      @phone_country = phone_country
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] schedule Object to be assigned
    def schedule=(schedule)
      validator = EnumAttributeValidator.new("String", ["MONTHLY", "YEARLY"])
      unless validator.valid?(schedule)
        raise ArgumentError.new("invalid value for \"schedule\", must be one of #{validator.allowable_values}.")
      end
      @schedule = schedule
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_number_variant Object to be assigned
    def phone_number_variant=(phone_number_variant)
      validator = EnumAttributeValidator.new("String", ["LOCAL", "MOBILE", "TOLL_FREE"])
      unless validator.valid?(phone_number_variant)
        raise ArgumentError.new("invalid value for \"phone_number_variant\", must be one of #{validator.allowable_values}.")
      end
      @phone_number_variant = phone_number_variant
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_provider Object to be assigned
    def phone_provider=(phone_provider)
      validator = EnumAttributeValidator.new("String", ["T1", "T2"])
      unless validator.valid?(phone_provider)
        raise ArgumentError.new("invalid value for \"phone_provider\", must be one of #{validator.allowable_values}.")
      end
      @phone_provider = phone_provider
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_line_filter Object to be assigned
    def phone_line_filter=(phone_line_filter)
      validator = EnumAttributeValidator.new("String", ["ANY", "OTP_FRIENDLY", "NON_VOIP"])
      unless validator.valid?(phone_line_filter)
        raise ArgumentError.new("invalid value for \"phone_line_filter\", must be one of #{validator.allowable_values}.")
      end
      @phone_line_filter = phone_line_filter
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          phone_country == o.phone_country &&
          name == o.name &&
          description == o.description &&
          tags == o.tags &&
          schedule == o.schedule &&
          phone_number_endpoint_override == o.phone_number_endpoint_override &&
          phone_number_variant == o.phone_number_variant &&
          phone_provider == o.phone_provider &&
          phone_line_filter == o.phone_line_filter
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [phone_country, name, description, tags, schedule, phone_number_endpoint_override, phone_number_variant, phone_provider, phone_line_filter].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if !attributes[self.class.attribute_map[key]]? && self.class.openapi_nullable.includes?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        ({} of Symbol => String).tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = .const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {} of Symbol => String
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.includes?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        ({} of Symbol => String).tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
