# #MailSlurp API
#
##MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
#
#The version of the OpenAPI document: 6.5.2
#Contact: contact@mailslurp.dev
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 5.1.1
#

require "time"

module 
  class DevicePreviewProviderProgressDto include JSON::Serializable
   include JSON::Serializable 
    @[JSON::Field(key: run, type: DevicePreviewRunDto)]
    property run : DevicePreviewRunDto


    @[JSON::Field(key: provider, type: String)]
    property provider : String


    @[JSON::Field(key: status, type: String)]
    property status : String


    @[JSON::Field(key: targetCount, type: Int64)]
    property target_count : Int64


    @[JSON::Field(key: readyCount, type: Int64)]
    property ready_count : Int64


    @[JSON::Field(key: failedCount, type: Int64)]
    property failed_count : Int64


    @[JSON::Field(key: capturingCount, type: Int64)]
    property capturing_count : Int64


    @[JSON::Field(key: pendingCount, type: Int64)]
    property pending_count : Int64


    @[JSON::Field(key: targets, type: Array(DevicePreviewTargetDto))]
    property targets : Array(DevicePreviewTargetDto)


    @[JSON::Field(key: screenshots, type: Array(DevicePreviewScreenshotDto))]
    property screenshots : Array(DevicePreviewScreenshotDto)

    class EnumAttributeValidator
      getter datatype : String
      getter allowable_values : Array(String)

      def initialize(datatype, allowable_values)
        @datatype = datatype
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.includes?(value)
      end
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@run : DevicePreviewRunDto, @provider : String, @status : String, @target_count : Int64, @ready_count : Int64, @failed_count : Int64, @capturing_count : Int64, @pending_count : Int64, @targets : Array(DevicePreviewTargetDto), @screenshots : Array(DevicePreviewScreenshotDto))
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @run.nil?
        invalid_properties.push("invalid value for \"run\", run cannot be nil.")
      end

      if @provider.nil?
        invalid_properties.push("invalid value for \"provider\", provider cannot be nil.")
      end

      if @status.nil?
        invalid_properties.push("invalid value for \"status\", status cannot be nil.")
      end

      if @target_count.nil?
        invalid_properties.push("invalid value for \"target_count\", target_count cannot be nil.")
      end

      if @ready_count.nil?
        invalid_properties.push("invalid value for \"ready_count\", ready_count cannot be nil.")
      end

      if @failed_count.nil?
        invalid_properties.push("invalid value for \"failed_count\", failed_count cannot be nil.")
      end

      if @capturing_count.nil?
        invalid_properties.push("invalid value for \"capturing_count\", capturing_count cannot be nil.")
      end

      if @pending_count.nil?
        invalid_properties.push("invalid value for \"pending_count\", pending_count cannot be nil.")
      end

      if @targets.nil?
        invalid_properties.push("invalid value for \"targets\", targets cannot be nil.")
      end

      if @screenshots.nil?
        invalid_properties.push("invalid value for \"screenshots\", screenshots cannot be nil.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @run.nil?
      return false if @provider.nil?
      provider_validator = EnumAttributeValidator.new("String", ["GMAIL", "OUTLOOK", "YAHOO"])
      return false unless provider_validator.valid?(@provider)
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new("String", ["PENDING", "CAPTURING", "PARTIAL_COMPLETE", "COMPLETE", "FAILED"])
      return false unless status_validator.valid?(@status)
      return false if @target_count.nil?
      return false if @ready_count.nil?
      return false if @failed_count.nil?
      return false if @capturing_count.nil?
      return false if @pending_count.nil?
      return false if @targets.nil?
      return false if @screenshots.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] provider Object to be assigned
    def provider=(provider)
      validator = EnumAttributeValidator.new("String", ["GMAIL", "OUTLOOK", "YAHOO"])
      unless validator.valid?(provider)
        raise ArgumentError.new("invalid value for \"provider\", must be one of #{validator.allowable_values}.")
      end
      @provider = provider
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new("String", ["PENDING", "CAPTURING", "PARTIAL_COMPLETE", "COMPLETE", "FAILED"])
      unless validator.valid?(status)
        raise ArgumentError.new("invalid value for \"status\", must be one of #{validator.allowable_values}.")
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          run == o.run &&
          provider == o.provider &&
          status == o.status &&
          target_count == o.target_count &&
          ready_count == o.ready_count &&
          failed_count == o.failed_count &&
          capturing_count == o.capturing_count &&
          pending_count == o.pending_count &&
          targets == o.targets &&
          screenshots == o.screenshots
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [run, provider, status, target_count, ready_count, failed_count, capturing_count, pending_count, targets, screenshots].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if !attributes[self.class.attribute_map[key]]? && self.class.openapi_nullable.includes?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        ({} of Symbol => String).tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = .const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {} of Symbol => String
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.includes?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        ({} of Symbol => String).tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
