# #MailSlurp API
#
##MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
#
#The version of the OpenAPI document: 6.5.2
#Contact: contact@mailslurp.dev
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 5.1.1
#

require "time"

module 
  # Conditions to apply to emails that you are waiting for
  class WaitForConditions include JSON::Serializable
   include JSON::Serializable 
    # ID of inbox to search within and apply conditions to. Essentially filtering the emails found to give a count.
    @[JSON::Field(key: inboxId, type: String)]
    property inbox_id : String


    # Number of results that should match conditions. Either exactly or at least this amount based on the `countType`. If count condition is not met and the timeout has not been reached the `waitFor` method will retry the operation.
    @[JSON::Field(key: count, type: Int32, nilable: true, emit_null: true)]
    property count : Int32


    # Max time in milliseconds to wait between retries if a `timeout` is specified.
    @[JSON::Field(key: delayTimeout, type: Int64, nilable: true, emit_null: true)]
    property delay_timeout : Int64


    # Max time in milliseconds to retry the `waitFor` operation until conditions are met.
    @[JSON::Field(key: timeout, type: Int64)]
    property timeout : Int64


    # Apply conditions only to **unread** emails. All emails begin with `read=false`. An email is marked `read=true` when an `EmailDto` representation of it has been returned to the user at least once. For example you have called `getEmail` or `waitForLatestEmail` etc., or you have viewed the email in the dashboard.
    @[JSON::Field(key: unreadOnly, type: Bool, nilable: true, emit_null: true)]
    property unread_only : Bool


    # How result size should be compared with the expected size. Exactly or at-least matching result?
    @[JSON::Field(key: countType, type: String, nilable: true, emit_null: true)]
    property count_type : String


    # Conditions that should be matched for an email to qualify for results. Each condition will be applied in order to each email within an inbox to filter a result list of matching emails you are waiting for.
    @[JSON::Field(key: matches, type: Array(MatchOption), nilable: true, emit_null: true)]
    property matches : Array(MatchOption)


    # Direction to sort matching emails by created time
    @[JSON::Field(key: sortDirection, type: String, nilable: true, emit_null: true)]
    property sort_direction : String


    # ISO Date Time earliest time of email to consider. Filter for matching emails that were received after this date
    @[JSON::Field(key: since, type: Time, nilable: true, emit_null: true)]
    property since : Time


    # ISO Date Time latest time of email to consider. Filter for matching emails that were received before this date
    @[JSON::Field(key: before, type: Time, nilable: true, emit_null: true)]
    property before : Time

    class EnumAttributeValidator
      getter datatype : String
      getter allowable_values : Array(String)

      def initialize(datatype, allowable_values)
        @datatype = datatype
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.includes?(value)
      end
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@inbox_id : String, @count : Int32 | Nil, @delay_timeout : Int64 | Nil, @timeout : Int64, @unread_only : Bool | Nil, @count_type : String | Nil, @matches : Array(MatchOption) | Nil, @sort_direction : String | Nil, @since : Time | Nil, @before : Time | Nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @inbox_id.nil?
        invalid_properties.push("invalid value for \"inbox_id\", inbox_id cannot be nil.")
      end

      if @timeout.nil?
        invalid_properties.push("invalid value for \"timeout\", timeout cannot be nil.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @inbox_id.nil?
      return false if @timeout.nil?
      count_type_validator = EnumAttributeValidator.new("String", ["EXACTLY", "ATLEAST"])
      return false unless count_type_validator.valid?(@count_type)
      sort_direction_validator = EnumAttributeValidator.new("String", ["ASC", "DESC"])
      return false unless sort_direction_validator.valid?(@sort_direction)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] count_type Object to be assigned
    def count_type=(count_type)
      validator = EnumAttributeValidator.new("String", ["EXACTLY", "ATLEAST"])
      unless validator.valid?(count_type)
        raise ArgumentError.new("invalid value for \"count_type\", must be one of #{validator.allowable_values}.")
      end
      @count_type = count_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sort_direction Object to be assigned
    def sort_direction=(sort_direction)
      validator = EnumAttributeValidator.new("String", ["ASC", "DESC"])
      unless validator.valid?(sort_direction)
        raise ArgumentError.new("invalid value for \"sort_direction\", must be one of #{validator.allowable_values}.")
      end
      @sort_direction = sort_direction
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          inbox_id == o.inbox_id &&
          count == o.count &&
          delay_timeout == o.delay_timeout &&
          timeout == o.timeout &&
          unread_only == o.unread_only &&
          count_type == o.count_type &&
          matches == o.matches &&
          sort_direction == o.sort_direction &&
          since == o.since &&
          before == o.before
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [inbox_id, count, delay_timeout, timeout, unread_only, count_type, matches, sort_direction, since, before].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if !attributes[self.class.attribute_map[key]]? && self.class.openapi_nullable.includes?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        ({} of Symbol => String).tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = .const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {} of Symbol => String
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.includes?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        ({} of Symbol => String).tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
