# #MailSlurp API
#
##MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
#
#The version of the OpenAPI document: 6.5.2
#Contact: contact@mailslurp.dev
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 5.1.1
#

require "uri"

module 
  class DeliverabilityTestControllerApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Cancel deliverability simulation job
    # Cancel a running or paused simulation job.
    # @param test_id [String] 
    # @param job_id [String] 
    # @return [DeliverabilitySimulationJobDto]
    def cancel_deliverability_simulation_job(test_id : String, job_id : String)
      data, _status_code, _headers = cancel_deliverability_simulation_job_with_http_info(test_id, job_id)
      data
    end

    # Cancel deliverability simulation job
    # Cancel a running or paused simulation job.
    # @param test_id [String] 
    # @param job_id [String] 
    # @return [Array<(DeliverabilitySimulationJobDto, Integer, Hash)>] DeliverabilitySimulationJobDto data, response status code and response headers
    def cancel_deliverability_simulation_job_with_http_info(test_id : String, job_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.cancel_deliverability_simulation_job ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.cancel_deliverability_simulation_job")
      end
      # verify the required parameter "job_id" is set
      if @api_client.config.client_side_validation && job_id.nil?
        raise ArgumentError.new("Missing the required parameter 'job_id' when calling DeliverabilityTestControllerApi.cancel_deliverability_simulation_job")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/simulation-jobs/{jobId}/cancel".sub("{" + "testId" + "}", URI.encode(test_id.to_s)).sub("{" + "jobId" + "}", URI.encode(job_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilitySimulationJobDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.cancel_deliverability_simulation_job",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#cancel_deliverability_simulation_job\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilitySimulationJobDto.from_json(data), status_code, headers
    end

    # Create deliverability simulation job
    # Create and start a simulation job for a running deliverability test. Only one active simulation job is allowed per user.
    # @param test_id [String] 
    # @param create_deliverability_simulation_job_options [CreateDeliverabilitySimulationJobOptions] 
    # @return [DeliverabilitySimulationJobDto]
    def create_deliverability_simulation_job(test_id : String, create_deliverability_simulation_job_options : CreateDeliverabilitySimulationJobOptions)
      data, _status_code, _headers = create_deliverability_simulation_job_with_http_info(test_id, create_deliverability_simulation_job_options)
      data
    end

    # Create deliverability simulation job
    # Create and start a simulation job for a running deliverability test. Only one active simulation job is allowed per user.
    # @param test_id [String] 
    # @param create_deliverability_simulation_job_options [CreateDeliverabilitySimulationJobOptions] 
    # @return [Array<(DeliverabilitySimulationJobDto, Integer, Hash)>] DeliverabilitySimulationJobDto data, response status code and response headers
    def create_deliverability_simulation_job_with_http_info(test_id : String, create_deliverability_simulation_job_options : CreateDeliverabilitySimulationJobOptions)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.create_deliverability_simulation_job ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.create_deliverability_simulation_job")
      end
      # verify the required parameter "create_deliverability_simulation_job_options" is set
      if @api_client.config.client_side_validation && create_deliverability_simulation_job_options.nil?
        raise ArgumentError.new("Missing the required parameter 'create_deliverability_simulation_job_options' when calling DeliverabilityTestControllerApi.create_deliverability_simulation_job")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/simulation-jobs".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = create_deliverability_simulation_job_options.to_json

      # return_type
      return_type = "DeliverabilitySimulationJobDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.create_deliverability_simulation_job",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#create_deliverability_simulation_job\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilitySimulationJobDto.from_json(data), status_code, headers
    end

    # Create deliverability/load test
    # Create a deliverability test for inboxes or phone numbers using ALL, PATTERN, or EXPLICIT selector scope.
    # @param create_deliverability_test_options [CreateDeliverabilityTestOptions] 
    # @return [DeliverabilityTestDto]
    def create_deliverability_test(create_deliverability_test_options : CreateDeliverabilityTestOptions)
      data, _status_code, _headers = create_deliverability_test_with_http_info(create_deliverability_test_options)
      data
    end

    # Create deliverability/load test
    # Create a deliverability test for inboxes or phone numbers using ALL, PATTERN, or EXPLICIT selector scope.
    # @param create_deliverability_test_options [CreateDeliverabilityTestOptions] 
    # @return [Array<(DeliverabilityTestDto, Integer, Hash)>] DeliverabilityTestDto data, response status code and response headers
    def create_deliverability_test_with_http_info(create_deliverability_test_options : CreateDeliverabilityTestOptions)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.create_deliverability_test ..."}
      end
      # verify the required parameter "create_deliverability_test_options" is set
      if @api_client.config.client_side_validation && create_deliverability_test_options.nil?
        raise ArgumentError.new("Missing the required parameter 'create_deliverability_test_options' when calling DeliverabilityTestControllerApi.create_deliverability_test")
      end
      # resource path
      local_var_path = "/test/deliverability"

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = create_deliverability_test_options.to_json

      # return_type
      return_type = "DeliverabilityTestDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.create_deliverability_test",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#create_deliverability_test\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilityTestDto.from_json(data), status_code, headers
    end

    # Delete deliverability/load test
    # Delete test and all persisted entity-level results.
    # @param test_id [String] 
    # @return [DeleteResult]
    def delete_deliverability_test(test_id : String)
      data, _status_code, _headers = delete_deliverability_test_with_http_info(test_id)
      data
    end

    # Delete deliverability/load test
    # Delete test and all persisted entity-level results.
    # @param test_id [String] 
    # @return [Array<(DeleteResult, Integer, Hash)>] DeleteResult data, response status code and response headers
    def delete_deliverability_test_with_http_info(test_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.delete_deliverability_test ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.delete_deliverability_test")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeleteResult"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:DELETE,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.delete_deliverability_test",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#delete_deliverability_test\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeleteResult.from_json(data), status_code, headers
    end

    # Duplicate deliverability/load test
    # Create a fresh deliverability test using an existing test configuration, including selector scope, exclusions, and expectations.
    # @param test_id [String] 
    # @return [DeliverabilityTestDto]
    def duplicate_deliverability_test(test_id : String)
      data, _status_code, _headers = duplicate_deliverability_test_with_http_info(test_id)
      data
    end

    # Duplicate deliverability/load test
    # Create a fresh deliverability test using an existing test configuration, including selector scope, exclusions, and expectations.
    # @param test_id [String] 
    # @return [Array<(DeliverabilityTestDto, Integer, Hash)>] DeliverabilityTestDto data, response status code and response headers
    def duplicate_deliverability_test_with_http_info(test_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.duplicate_deliverability_test ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.duplicate_deliverability_test")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/duplicate".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilityTestDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.duplicate_deliverability_test",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#duplicate_deliverability_test\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilityTestDto.from_json(data), status_code, headers
    end

    # Export deliverability/load test report as PDF
    # Export a PDF report for a terminal deliverability test (COMPLETE, FAILED, or STOPPED), including configuration, summary outcomes, and detailed entity-level results.
    # @param test_id [String] 
    # @return [nil]
    def export_deliverability_test_report(test_id : String)
      export_deliverability_test_report_with_http_info(test_id)
      nil
    end

    # Export deliverability/load test report as PDF
    # Export a PDF report for a terminal deliverability test (COMPLETE, FAILED, or STOPPED), including configuration, summary outcomes, and detailed entity-level results.
    # @param test_id [String] 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def export_deliverability_test_report_with_http_info(test_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.export_deliverability_test_report ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.export_deliverability_test_report")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/report/export".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.export_deliverability_test_report",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#export_deliverability_test_report\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # Export deliverability/load test entity results as CSV
    # Export per-entity deliverability results including expectation-level pass/fail counts. The latest status is evaluated with the same polling safeguards before export.
    # @param test_id [String] 
    # @return [nil]
    def export_deliverability_test_results(test_id : String, matched : Bool?)
      export_deliverability_test_results_with_http_info(test_id, matched)
      nil
    end

    # Export deliverability/load test entity results as CSV
    # Export per-entity deliverability results including expectation-level pass/fail counts. The latest status is evaluated with the same polling safeguards before export.
    # @param test_id [String] 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def export_deliverability_test_results_with_http_info(test_id : String, matched : Bool?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.export_deliverability_test_results ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.export_deliverability_test_results")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/results/export".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new
      query_params[:"matched"] = matched

      # header parameters
      header_params = Hash(String, String).new

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.export_deliverability_test_results",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#export_deliverability_test_results\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # Get deliverability analytics time series
    # Compare deliverability runs over a time range with bucketed chart metrics and run-level rows for table views.
    # @return [DeliverabilityAnalyticsSeriesDto]
    def get_deliverability_analytics_series(since : Time?, before : Time?, scope : String?, bucket : String?, run_limit : Int32?)
      data, _status_code, _headers = get_deliverability_analytics_series_with_http_info(since, before, scope, bucket, run_limit)
      data
    end

    # Get deliverability analytics time series
    # Compare deliverability runs over a time range with bucketed chart metrics and run-level rows for table views.
    # @return [Array<(DeliverabilityAnalyticsSeriesDto, Integer, Hash)>] DeliverabilityAnalyticsSeriesDto data, response status code and response headers
    def get_deliverability_analytics_series_with_http_info(since : Time?, before : Time?, scope : String?, bucket : String?, run_limit : Int32?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.get_deliverability_analytics_series ..."}
      end
      allowable_values = ["INBOX", "PHONE"]
      if @api_client.config.client_side_validation && scope && !allowable_values.includes?(scope)
        raise ArgumentError.new("invalid value for \"scope\", must be one of #{allowable_values}")
      end
      allowable_values = ["HOUR", "DAY"]
      if @api_client.config.client_side_validation && bucket && !allowable_values.includes?(bucket)
        raise ArgumentError.new("invalid value for \"bucket\", must be one of #{allowable_values}")
      end
      # resource path
      local_var_path = "/test/deliverability/analytics/series"

      # query parameters
      query_params = Hash(Symbol, String).new
      query_params[:"since"] = since
      query_params[:"before"] = before
      query_params[:"scope"] = scope
      query_params[:"bucket"] = bucket
      query_params[:"runLimit"] = run_limit

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilityAnalyticsSeriesDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.get_deliverability_analytics_series",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#get_deliverability_analytics_series\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilityAnalyticsSeriesDto.from_json(data), status_code, headers
    end

    # Get deliverability failure hotspots
    # Find commonly failing entities and phone country/variant dimensions across deliverability runs in a time range.
    # @return [DeliverabilityFailureHotspotsDto]
    def get_deliverability_failure_hotspots(since : Time?, before : Time?, scope : String?, limit : Int32?)
      data, _status_code, _headers = get_deliverability_failure_hotspots_with_http_info(since, before, scope, limit)
      data
    end

    # Get deliverability failure hotspots
    # Find commonly failing entities and phone country/variant dimensions across deliverability runs in a time range.
    # @return [Array<(DeliverabilityFailureHotspotsDto, Integer, Hash)>] DeliverabilityFailureHotspotsDto data, response status code and response headers
    def get_deliverability_failure_hotspots_with_http_info(since : Time?, before : Time?, scope : String?, limit : Int32?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.get_deliverability_failure_hotspots ..."}
      end
      allowable_values = ["INBOX", "PHONE"]
      if @api_client.config.client_side_validation && scope && !allowable_values.includes?(scope)
        raise ArgumentError.new("invalid value for \"scope\", must be one of #{allowable_values}")
      end
      # resource path
      local_var_path = "/test/deliverability/analytics/hotspots"

      # query parameters
      query_params = Hash(Symbol, String).new
      query_params[:"since"] = since
      query_params[:"before"] = before
      query_params[:"scope"] = scope
      query_params[:"limit"] = limit

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilityFailureHotspotsDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.get_deliverability_failure_hotspots",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#get_deliverability_failure_hotspots\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilityFailureHotspotsDto.from_json(data), status_code, headers
    end

    # Get deliverability simulation job
    # Get simulation job status and progress counters.
    # @param test_id [String] 
    # @param job_id [String] 
    # @return [DeliverabilitySimulationJobDto]
    def get_deliverability_simulation_job(test_id : String, job_id : String)
      data, _status_code, _headers = get_deliverability_simulation_job_with_http_info(test_id, job_id)
      data
    end

    # Get deliverability simulation job
    # Get simulation job status and progress counters.
    # @param test_id [String] 
    # @param job_id [String] 
    # @return [Array<(DeliverabilitySimulationJobDto, Integer, Hash)>] DeliverabilitySimulationJobDto data, response status code and response headers
    def get_deliverability_simulation_job_with_http_info(test_id : String, job_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.get_deliverability_simulation_job ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.get_deliverability_simulation_job")
      end
      # verify the required parameter "job_id" is set
      if @api_client.config.client_side_validation && job_id.nil?
        raise ArgumentError.new("Missing the required parameter 'job_id' when calling DeliverabilityTestControllerApi.get_deliverability_simulation_job")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/simulation-jobs/{jobId}".sub("{" + "testId" + "}", URI.encode(test_id.to_s)).sub("{" + "jobId" + "}", URI.encode(job_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilitySimulationJobDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.get_deliverability_simulation_job",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#get_deliverability_simulation_job\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilitySimulationJobDto.from_json(data), status_code, headers
    end

    # Get deliverability simulation job events
    # Get paged simulation events including send successes and failures.
    # @param test_id [String] 
    # @param job_id [String] 
    # @return [DeliverabilitySimulationJobEventPageDto]
    def get_deliverability_simulation_job_events(test_id : String, job_id : String, page : Int32?, size : Int32?, sort : String?)
      data, _status_code, _headers = get_deliverability_simulation_job_events_with_http_info(test_id, job_id, page, size, sort)
      data
    end

    # Get deliverability simulation job events
    # Get paged simulation events including send successes and failures.
    # @param test_id [String] 
    # @param job_id [String] 
    # @return [Array<(DeliverabilitySimulationJobEventPageDto, Integer, Hash)>] DeliverabilitySimulationJobEventPageDto data, response status code and response headers
    def get_deliverability_simulation_job_events_with_http_info(test_id : String, job_id : String, page : Int32?, size : Int32?, sort : String?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.get_deliverability_simulation_job_events ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.get_deliverability_simulation_job_events")
      end
      # verify the required parameter "job_id" is set
      if @api_client.config.client_side_validation && job_id.nil?
        raise ArgumentError.new("Missing the required parameter 'job_id' when calling DeliverabilityTestControllerApi.get_deliverability_simulation_job_events")
      end
      allowable_values = ["ASC", "DESC"]
      if @api_client.config.client_side_validation && sort && !allowable_values.includes?(sort)
        raise ArgumentError.new("invalid value for \"sort\", must be one of #{allowable_values}")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/simulation-jobs/{jobId}/events".sub("{" + "testId" + "}", URI.encode(test_id.to_s)).sub("{" + "jobId" + "}", URI.encode(job_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new
      query_params[:"page"] = page
      query_params[:"size"] = size
      query_params[:"sort"] = sort

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilitySimulationJobEventPageDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.get_deliverability_simulation_job_events",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#get_deliverability_simulation_job_events\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilitySimulationJobEventPageDto.from_json(data), status_code, headers
    end

    # Get deliverability/load test
    # Get deliverability test configuration and latest progress counters.
    # @param test_id [String] 
    # @return [DeliverabilityTestDto]
    def get_deliverability_test(test_id : String)
      data, _status_code, _headers = get_deliverability_test_with_http_info(test_id)
      data
    end

    # Get deliverability/load test
    # Get deliverability test configuration and latest progress counters.
    # @param test_id [String] 
    # @return [Array<(DeliverabilityTestDto, Integer, Hash)>] DeliverabilityTestDto data, response status code and response headers
    def get_deliverability_test_with_http_info(test_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.get_deliverability_test ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.get_deliverability_test")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilityTestDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.get_deliverability_test",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#get_deliverability_test\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilityTestDto.from_json(data), status_code, headers
    end

    # Get deliverability/load test entity results
    # Get paged per-entity expectation results with optional matched/unmatched filtering.
    # @param test_id [String] 
    # @return [DeliverabilityEntityResultPageDto]
    def get_deliverability_test_results(test_id : String, matched : Bool?, page : Int32?, size : Int32?, sort : String?)
      data, _status_code, _headers = get_deliverability_test_results_with_http_info(test_id, matched, page, size, sort)
      data
    end

    # Get deliverability/load test entity results
    # Get paged per-entity expectation results with optional matched/unmatched filtering.
    # @param test_id [String] 
    # @return [Array<(DeliverabilityEntityResultPageDto, Integer, Hash)>] DeliverabilityEntityResultPageDto data, response status code and response headers
    def get_deliverability_test_results_with_http_info(test_id : String, matched : Bool?, page : Int32?, size : Int32?, sort : String?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.get_deliverability_test_results ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.get_deliverability_test_results")
      end
      allowable_values = ["ASC", "DESC"]
      if @api_client.config.client_side_validation && sort && !allowable_values.includes?(sort)
        raise ArgumentError.new("invalid value for \"sort\", must be one of #{allowable_values}")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/results".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new
      query_params[:"matched"] = matched
      query_params[:"page"] = page
      query_params[:"size"] = size
      query_params[:"sort"] = sort

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilityEntityResultPageDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.get_deliverability_test_results",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#get_deliverability_test_results\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilityEntityResultPageDto.from_json(data), status_code, headers
    end

    # List deliverability/load tests
    # List deliverability tests for the authenticated account.
    # @return [DeliverabilityTestPageDto]
    def get_deliverability_tests(page : Int32?, size : Int32?, sort : String?)
      data, _status_code, _headers = get_deliverability_tests_with_http_info(page, size, sort)
      data
    end

    # List deliverability/load tests
    # List deliverability tests for the authenticated account.
    # @return [Array<(DeliverabilityTestPageDto, Integer, Hash)>] DeliverabilityTestPageDto data, response status code and response headers
    def get_deliverability_tests_with_http_info(page : Int32?, size : Int32?, sort : String?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.get_deliverability_tests ..."}
      end
      allowable_values = ["ASC", "DESC"]
      if @api_client.config.client_side_validation && sort && !allowable_values.includes?(sort)
        raise ArgumentError.new("invalid value for \"sort\", must be one of #{allowable_values}")
      end
      # resource path
      local_var_path = "/test/deliverability"

      # query parameters
      query_params = Hash(Symbol, String).new
      query_params[:"page"] = page
      query_params[:"size"] = size
      query_params[:"sort"] = sort

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilityTestPageDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.get_deliverability_tests",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#get_deliverability_tests\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilityTestPageDto.from_json(data), status_code, headers
    end

    # Get latest deliverability simulation job
    # Get the most recent simulation job for a deliverability test.
    # @param test_id [String] 
    # @return [DeliverabilitySimulationJobDto]
    def get_latest_deliverability_simulation_job(test_id : String)
      data, _status_code, _headers = get_latest_deliverability_simulation_job_with_http_info(test_id)
      data
    end

    # Get latest deliverability simulation job
    # Get the most recent simulation job for a deliverability test.
    # @param test_id [String] 
    # @return [Array<(DeliverabilitySimulationJobDto, Integer, Hash)>] DeliverabilitySimulationJobDto data, response status code and response headers
    def get_latest_deliverability_simulation_job_with_http_info(test_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.get_latest_deliverability_simulation_job ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.get_latest_deliverability_simulation_job")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/simulation-jobs/latest".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilitySimulationJobDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.get_latest_deliverability_simulation_job",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#get_latest_deliverability_simulation_job\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilitySimulationJobDto.from_json(data), status_code, headers
    end

    # Pause deliverability simulation job
    # Pause a running simulation job.
    # @param test_id [String] 
    # @param job_id [String] 
    # @return [DeliverabilitySimulationJobDto]
    def pause_deliverability_simulation_job(test_id : String, job_id : String)
      data, _status_code, _headers = pause_deliverability_simulation_job_with_http_info(test_id, job_id)
      data
    end

    # Pause deliverability simulation job
    # Pause a running simulation job.
    # @param test_id [String] 
    # @param job_id [String] 
    # @return [Array<(DeliverabilitySimulationJobDto, Integer, Hash)>] DeliverabilitySimulationJobDto data, response status code and response headers
    def pause_deliverability_simulation_job_with_http_info(test_id : String, job_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.pause_deliverability_simulation_job ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.pause_deliverability_simulation_job")
      end
      # verify the required parameter "job_id" is set
      if @api_client.config.client_side_validation && job_id.nil?
        raise ArgumentError.new("Missing the required parameter 'job_id' when calling DeliverabilityTestControllerApi.pause_deliverability_simulation_job")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/simulation-jobs/{jobId}/pause".sub("{" + "testId" + "}", URI.encode(test_id.to_s)).sub("{" + "jobId" + "}", URI.encode(job_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilitySimulationJobDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.pause_deliverability_simulation_job",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#pause_deliverability_simulation_job\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilitySimulationJobDto.from_json(data), status_code, headers
    end

    # Pause deliverability/load test
    # Pause a RUNNING or SCHEDULED deliverability test.
    # @param test_id [String] 
    # @return [DeliverabilityTestDto]
    def pause_deliverability_test(test_id : String)
      data, _status_code, _headers = pause_deliverability_test_with_http_info(test_id)
      data
    end

    # Pause deliverability/load test
    # Pause a RUNNING or SCHEDULED deliverability test.
    # @param test_id [String] 
    # @return [Array<(DeliverabilityTestDto, Integer, Hash)>] DeliverabilityTestDto data, response status code and response headers
    def pause_deliverability_test_with_http_info(test_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.pause_deliverability_test ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.pause_deliverability_test")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/pause".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilityTestDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.pause_deliverability_test",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#pause_deliverability_test\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilityTestDto.from_json(data), status_code, headers
    end

    # Poll deliverability/load test status
    # Poll test progress. Evaluation is throttled with a 5-second cache window to protect backing data stores.
    # @param test_id [String] 
    # @return [DeliverabilityPollStatusResultDto]
    def poll_deliverability_test_status(test_id : String)
      data, _status_code, _headers = poll_deliverability_test_status_with_http_info(test_id)
      data
    end

    # Poll deliverability/load test status
    # Poll test progress. Evaluation is throttled with a 5-second cache window to protect backing data stores.
    # @param test_id [String] 
    # @return [Array<(DeliverabilityPollStatusResultDto, Integer, Hash)>] DeliverabilityPollStatusResultDto data, response status code and response headers
    def poll_deliverability_test_status_with_http_info(test_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.poll_deliverability_test_status ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.poll_deliverability_test_status")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/status".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilityPollStatusResultDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.poll_deliverability_test_status",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#poll_deliverability_test_status\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilityPollStatusResultDto.from_json(data), status_code, headers
    end

    # Resume deliverability simulation job
    # Resume a paused simulation job.
    # @param test_id [String] 
    # @param job_id [String] 
    # @return [DeliverabilitySimulationJobDto]
    def resume_deliverability_simulation_job(test_id : String, job_id : String)
      data, _status_code, _headers = resume_deliverability_simulation_job_with_http_info(test_id, job_id)
      data
    end

    # Resume deliverability simulation job
    # Resume a paused simulation job.
    # @param test_id [String] 
    # @param job_id [String] 
    # @return [Array<(DeliverabilitySimulationJobDto, Integer, Hash)>] DeliverabilitySimulationJobDto data, response status code and response headers
    def resume_deliverability_simulation_job_with_http_info(test_id : String, job_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.resume_deliverability_simulation_job ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.resume_deliverability_simulation_job")
      end
      # verify the required parameter "job_id" is set
      if @api_client.config.client_side_validation && job_id.nil?
        raise ArgumentError.new("Missing the required parameter 'job_id' when calling DeliverabilityTestControllerApi.resume_deliverability_simulation_job")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/simulation-jobs/{jobId}/resume".sub("{" + "testId" + "}", URI.encode(test_id.to_s)).sub("{" + "jobId" + "}", URI.encode(job_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilitySimulationJobDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.resume_deliverability_simulation_job",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#resume_deliverability_simulation_job\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilitySimulationJobDto.from_json(data), status_code, headers
    end

    # Start or resume deliverability/load test
    # Start a CREATED test or resume a PAUSED/SCHEDULED test.
    # @param test_id [String] 
    # @return [DeliverabilityTestDto]
    def start_deliverability_test(test_id : String)
      data, _status_code, _headers = start_deliverability_test_with_http_info(test_id)
      data
    end

    # Start or resume deliverability/load test
    # Start a CREATED test or resume a PAUSED/SCHEDULED test.
    # @param test_id [String] 
    # @return [Array<(DeliverabilityTestDto, Integer, Hash)>] DeliverabilityTestDto data, response status code and response headers
    def start_deliverability_test_with_http_info(test_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.start_deliverability_test ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.start_deliverability_test")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/start".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilityTestDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.start_deliverability_test",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#start_deliverability_test\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilityTestDto.from_json(data), status_code, headers
    end

    # Stop deliverability/load test
    # Stop a deliverability test and mark it terminal.
    # @param test_id [String] 
    # @return [DeliverabilityTestDto]
    def stop_deliverability_test(test_id : String)
      data, _status_code, _headers = stop_deliverability_test_with_http_info(test_id)
      data
    end

    # Stop deliverability/load test
    # Stop a deliverability test and mark it terminal.
    # @param test_id [String] 
    # @return [Array<(DeliverabilityTestDto, Integer, Hash)>] DeliverabilityTestDto data, response status code and response headers
    def stop_deliverability_test_with_http_info(test_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.stop_deliverability_test ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.stop_deliverability_test")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}/stop".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeliverabilityTestDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.stop_deliverability_test",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#stop_deliverability_test\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilityTestDto.from_json(data), status_code, headers
    end

    # Update deliverability/load test
    # Update metadata, timeout, and expectations for a non-running non-terminal test.
    # @param test_id [String] 
    # @param update_deliverability_test_options [UpdateDeliverabilityTestOptions] 
    # @return [DeliverabilityTestDto]
    def update_deliverability_test(test_id : String, update_deliverability_test_options : UpdateDeliverabilityTestOptions)
      data, _status_code, _headers = update_deliverability_test_with_http_info(test_id, update_deliverability_test_options)
      data
    end

    # Update deliverability/load test
    # Update metadata, timeout, and expectations for a non-running non-terminal test.
    # @param test_id [String] 
    # @param update_deliverability_test_options [UpdateDeliverabilityTestOptions] 
    # @return [Array<(DeliverabilityTestDto, Integer, Hash)>] DeliverabilityTestDto data, response status code and response headers
    def update_deliverability_test_with_http_info(test_id : String, update_deliverability_test_options : UpdateDeliverabilityTestOptions)
      if @api_client.config.debugging
        Log.debug {"Calling API: DeliverabilityTestControllerApi.update_deliverability_test ..."}
      end
      # verify the required parameter "test_id" is set
      if @api_client.config.client_side_validation && test_id.nil?
        raise ArgumentError.new("Missing the required parameter 'test_id' when calling DeliverabilityTestControllerApi.update_deliverability_test")
      end
      # verify the required parameter "update_deliverability_test_options" is set
      if @api_client.config.client_side_validation && update_deliverability_test_options.nil?
        raise ArgumentError.new("Missing the required parameter 'update_deliverability_test_options' when calling DeliverabilityTestControllerApi.update_deliverability_test")
      end
      # resource path
      local_var_path = "/test/deliverability/{testId}".sub("{" + "testId" + "}", URI.encode(test_id.to_s))

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = update_deliverability_test_options.to_json

      # return_type
      return_type = "DeliverabilityTestDto"

      # auth_names
      auth_names = ["API_KEY"]

      data, status_code, headers = @api_client.call_api(:PATCH,
                                                        local_var_path,
                                                        :"DeliverabilityTestControllerApi.update_deliverability_test",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DeliverabilityTestControllerApi#update_deliverability_test\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeliverabilityTestDto.from_json(data), status_code, headers
    end
  end
end
